server:
  host:
    front: http://127.0.0.1
  port: 8080
spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/test
    username: root
    password: dkwktm45
    driver-class-name: org.mariadb.jdbc.Driver
  profiles:
    active:
      on-profile: redis
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
    add-properties: false
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jwt:
    secret: govlepel@$&
